[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "risklib"
version = "0.0.1"
description = "Risk management library (VaR, ES, backtesting, Monte Carlo)"

[tool.setuptools.packages.find]
where = ["."]
exclude = ["Examples*"]